apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: felixacr.azurecr.io/microblog:latest
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              value: "my-secret-key"
            - name: DATABASE_URL
              value: "mysql+pymysql://microblog:novirus@mysql/microblog"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-app