---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: "microblog"
            - name: MYSQL_USER
              value: "microblog"
            - name: MYSQL_PASSWORD
              value: "novirus"
          ports:
            - containerPort: 3306
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql
