name: CI/CD Pipeline

on:
  push:
    branches: [ flask2024 ]
    paths:
      - 'app'
      - '.github/workflows/ussrelab-ci-cd.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: felixacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image for Flask App
      run: |
        docker build -t felixacr.azurecr.io/microblog:latest .
        docker push felixacr.azurecr.io/microblog:latest

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1

    - name: Connect to Azure Kubernetes Service
      run: |
        az aks get-credentials --resource-group <myResourceGroup> --name <myAKSCluster>

    - name: Deploy Flask App to AKS
      run: |
        kubectl apply -f k8s-deployment/flask-deployment.yaml
