name: USSRELab CI/CD Pipeline

on:
  push:
    branches: [ flask2024 ]
    paths:
      - 'app'
      - '.github/workflows/ussrelab-ci-cd.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.acr_name }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image for Flask App
      run: |
        docker build -t ${{ secrets.acr_name }}.azurecr.io/microblog:latest .
        docker push ${{ secrets.acr_name }}.azurecr.io/microblog:latest
    
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Connect to Azure Kubernetes Service
      run: |
        az aks get-credentials --resource-group ${{ secrets.resource_group }} --name ${{ secrets.cluster_name }}

    - name: Deploy Flask App to AKS
      run: |
        kubectl apply -f flask-deployment.yaml
        